#branches:
#  only:
#    - master

environment:
  matrix:
#    - TARGET: MINGW64
    - TARGET: MINGW32

for:
#  -
#    matrix:
#      only:
#        - TARGET: MINGW64
#    environment:
#      MSYSTEM: MINGW64
#      PATH: C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%
  -
    matrix:
      only:
        - TARGET: MINGW32
    environment:
      MSYSTEM: MINGW32
      PATH: C:\msys64\mingw32\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%

install:
  - echo %TARGET%
#  - echo %MSYSTEM%
#  - echo %PATH%
#  - cd
#  - dir

build_script:
  - bash -lc "gcc -v"
  - bash -lc "pwd"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && ./autogen.sh"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && ./configure --enable-threads=win32 --enable-large-config CPPFLAGS="-DNO_ABORT_MSGBOX "

test_script:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && make check"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && COUNT=0; ERRCNT=0; while ((COUNT<500)); do ./gctest.exe || { ((ERRCNT++)); cat .libs/gctest.gc.log; }; ((COUNT++)); echo $COUNT $ERRCNT; done; exit $((ERRCNT>0))"

